# -*- coding: utf-8 -*-
"""2025_Barttovik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DGuwZacOQTmcowLMgOXa6rHRBKoQq1E
"""

import pandas as pd

# Define the correct T-Rank column names
cols = [
    'team', 'adjoe', 'adjde', 'barthag', 'record', 'wins', 'games',
    'tempo', 'off_efg', 'def_efg', 'off_tor', 'def_tor', 'off_orb',
    'def_orb', 'off_ftrate', 'def_ftrate', 'off_2p', 'def_2p',
    'off_3p', 'def_3p', 'off_3pr', 'def_3pr', 'off_ft', 'def_ft',
    'avg_hgt', 'eff_hgt', 'c_hgt', 'pg_hgt', 'sg_hgt', 'sf_hgt',
    'pf_hgt', 'year', 'col32', 'col33', 'adj_margin', 'wab', 'col36'
]

df = pd.read_csv('/content/trank_data.csv', header=0, names=cols)

# Add back the header row that got eaten (UC Santa Barbara)
uc_sb = pd.DataFrame([[
    'UC Santa Barbara', 108.474, 107.964, 0.513531, '21-13', 21, 34,
    54.6, 48.9, 29.7, None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None, None, None, None,
    None, None, 2025, None, None, -8.07099, 77.2, None
]], columns=cols)

df = pd.concat([uc_sb, df], ignore_index=True)

# Drop mostly-empty junk columns
df = df.drop(columns=['col32', 'col33', 'col36'])

# Convert numeric columns
for col in df.columns[1:]:
    df[col] = pd.to_numeric(df[col], errors='ignore')

print(df.shape)
print(df[['team', 'adjoe', 'adjde', 'barthag', 'adj_margin', 'wab']].head(10))

# Top 10 Offensive Teams (higher adjoe = better)
top_offense = df[['team', 'adjoe']].sort_values('adjoe', ascending=False).head(10).reset_index(drop=True)

# Top 10 Defensive Teams (lower adjde = better)
top_defense = df[['team', 'adjde']].sort_values('adjde', ascending=True).head(10).reset_index(drop=True)

# Combine side by side
top10 = pd.concat([top_offense, top_defense], axis=1)
top10.columns = ['Off Team', 'AdjOE', 'Def Team', 'AdjDE']
top10.index += 1  # start ranking at 1

print(top10.to_string())

df.head(5)

# Drop columns with excessive NaN values and irrelevant metadata
bart_data = df[[
    'team',         # Team name
    'adjoe',        # Adjusted Offensive Efficiency (points per 100 possessions)
    'adjde',        # Adjusted Defensive Efficiency (points allowed per 100 possessions)
    'barthag',      # Overall team strength (win probability vs avg D1 team, 0-1)
    'adj_margin',   # adjoe minus adjde — simple net efficiency
    'wab',          # Wins Above Bubble — measures resume strength
    'record',       # Win-loss record
    'wins',         # Total wins
    'games',        # Total games played
    'tempo',        # Adjusted tempo (possessions per game)
    'off_efg',      # Offensive effective field goal %
    'def_efg',      # Defensive effective field goal % (lower = better defense)
    'year'          # Season year
]].copy()

# Drop any rows where core metrics are missing
bart_data = bart_data.dropna(subset=['adjoe', 'adjde', 'barthag', 'adj_margin', 'wab'])

# Reset index cleanly
bart_data = bart_data.reset_index(drop=True)

# Final dataset: 363 D1 teams for 2025 season with key efficiency and resume metrics
print(bart_data.shape)
bart_data.head()

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# ── Abbreviation map ──────────────────────────────────────────────────────────
abbrev_map = {
    'UC Santa Barbara': 'UCSB', 'North Carolina': 'UNC', 'Duke': 'Duke',
    'Kentucky': 'UK', 'Kansas': 'KU', 'Gonzaga': 'Gonz', 'Houston': 'HOU',
    'Auburn': 'AUB', 'Tennessee': 'TENN', 'Florida': 'UF', 'Alabama': 'ALA',
    'Michigan State': 'MSU', 'Purdue': 'PUR', 'Wisconsin': 'WIS',
    'Illinois': 'ILL', 'Indiana': 'IND', 'Iowa': 'IOWA', 'Ohio State': 'OSU',
    'Michigan': 'MICH', 'Northwestern': 'NW', 'Minnesota': 'MINN',
    'Nebraska': 'NEB', 'Penn State': 'PSU', 'Rutgers': 'RU',
    'Maryland': 'UMD', 'UCLA': 'UCLA', 'USC': 'USC', 'Arizona': 'ARIZ',
    'Oregon': 'ORE', 'Washington': 'WASH', 'Colorado': 'COL',
    'Utah': 'UTAH', 'Stanford': 'STAN', 'California': 'CAL',
    'Arizona State': 'ASU', 'Washington State': 'WSU', 'Oregon State': 'ORST',
    'Texas': 'TEX', 'Oklahoma': 'OU', 'Baylor': 'BAY', 'TCU': 'TCU',
    'Texas Tech': 'TTU', 'West Virginia': 'WVU', 'Iowa State': 'ISU',
    'Kansas State': 'KSU', 'Oklahoma State': 'OKST', 'Cincinnati': 'CIN',
    'UCF': 'UCF', 'BYU': 'BYU', 'Houston Baptist': 'HBU',
    'Connecticut': 'UCONN', 'Villanova': 'NOVA', 'Creighton': 'CREI',
    'Xavier': 'XAV', 'Marquette': 'MU', 'Seton Hall': 'SHU',
    'Providence': 'PROV', 'Butler': 'BUT', 'DePaul': 'DEP',
    'Georgetown': 'GTOWN', 'St. John\'s': 'STJ', 'Louisville': 'LOU',
    'Syracuse': 'SYR', 'Pittsburgh': 'PITT', 'Virginia': 'UVA',
    'Virginia Tech': 'VT', 'Notre Dame': 'ND', 'Wake Forest': 'WAKE',
    'NC State': 'NCST', 'Clemson': 'CLEM', 'Georgia Tech': 'GT',
    'Miami FL': 'MIA', 'Boston College': 'BC', 'Florida State': 'FSU',
    'Memphis': 'MEM', 'Wichita State': 'WICH', 'Temple': 'TEM',
    'SMU': 'SMU', 'Tulsa': 'TLSA', 'East Carolina': 'ECU',
    'Tulane': 'TUL', 'South Florida': 'USF', 'Navy': 'NAVY',
    'Arkansas': 'ARK', 'LSU': 'LSU', 'Mississippi State': 'MSST',
    'Ole Miss': 'MISS', 'Georgia': 'UGA', 'South Carolina': 'SC',
    'Missouri': 'MIZZ', 'Texas A&M': 'TAMU', 'Vanderbilt': 'VAN',
    'Mississippi': 'MISS', 'San Diego State': 'SDSU', 'UNLV': 'UNLV',
    'Fresno State': 'FRES', 'Boise State': 'BSU', 'Nevada': 'NEV',
    'New Mexico': 'UNM', 'Utah State': 'UTST', 'Wyoming': 'WYO',
    'Colorado State': 'COST', 'Air Force': 'AF', 'San Jose State': 'SJSU',
    'Arkansas Pine Bluff': 'UAPB', 'Toledo': 'TOL', 'Louisiana': 'ULL',
    'Central Michigan': 'CMU', 'Saint Mary\'s': 'SMC', 'Vermont': 'UVM',
    'Liberty': 'LIB', 'Belmont': 'BEL', 'Murray State': 'MUR',
    'Morehead State': 'MORE', 'Cleveland State': 'CLEV',
    'Wright State': 'WRST', 'Valparaiso': 'VAL', 'Drake': 'DRK',
    'Bradley': 'BRAD', 'Loyola Chicago': 'LOY', 'Northern Iowa': 'UNI',
    'Indiana State': 'INST', 'Missouri State': 'MOST', 'Evansville': 'EVA',
    'Southern Illinois': 'SIU', 'Illinois State': 'ILST',
}

def abbreviate(name):
    if name in abbrev_map:
        return abbrev_map[name]
    # Auto-abbreviate unknowns: take first letters of each word, max 4 chars
    words = name.split()
    if len(words) == 1:
        return name[:4].upper()
    return ''.join(w[0] for w in words).upper()[:5]

bart_data['abbrev'] = bart_data['team'].apply(abbreviate)

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(18, 12))
ax.set_facecolor('#0f0f1a')
fig.patch.set_facecolor('#0f0f1a')

# Scatter
sc = ax.scatter(
    bart_data['tempo'],
    bart_data['adj_margin'],
    c=bart_data['barthag'],
    cmap='plasma',
    s=40,
    alpha=0.85,
    zorder=3
)

# Trapezoid of Excellence overlay
# "Elite zone": fast tempo + high margin
trap_x = [60, 65, 72, 75, 72, 65, 60]
trap_y = [8, 8, 15, 20, 30, 30, 20]
trap = patches.Polygon(
    list(zip(trap_x, trap_y)),
    closed=True,
    fill=True,
    facecolor='cyan',
    edgecolor='cyan',
    alpha=0.07,
    zorder=2,
    linewidth=1.5,
    linestyle='--'
)
ax.add_patch(trap)
ax.text(66, 28, '🏆 Trapezoid of Excellence', color='cyan',
        fontsize=9, alpha=0.7, fontstyle='italic')

# Team labels
for _, row in bart_data.iterrows():
    ax.annotate(
        row['abbrev'],
        (row['tempo'], row['adj_margin']),
        fontsize=5.5,
        color='white',
        alpha=0.75,
        xytext=(3, 3),
        textcoords='offset points'
    )

# Reference lines
ax.axhline(0, color='gray', linewidth=0.5, linestyle='--', alpha=0.4)
ax.axvline(bart_data['tempo'].mean(), color='gray', linewidth=0.5,
           linestyle='--', alpha=0.4)

# Labels & formatting
ax.set_xlabel('Tempo (Possessions per Game)', color='white', fontsize=12)
ax.set_ylabel('Net Rating (Adj Margin)', color='white', fontsize=12)
ax.set_title('Trapezoid of Excellence — Pace vs Net Rating (2025)',
             color='white', fontsize=15, fontweight='bold', pad=15)
ax.tick_params(colors='white')
for spine in ax.spines.values():
    spine.set_edgecolor('#333355')

cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('Barthag (Team Strength)', color='white', fontsize=9)
cbar.ax.yaxis.set_tick_params(color='white')
plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white')

plt.tight_layout()
plt.savefig('trapezoid_of_excellence.png', dpi=150, bbox_inches='tight',
            facecolor='#0f0f1a')
plt.show()

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from scipy import stats

# ── Filter to relevant teams only (positive or near-positive margin) ──────────
plot_data = bart_data[bart_data['adj_margin'] >= 5].copy()
plot_data['abbrev'] = plot_data['team'].apply(abbreviate)

fig, ax = plt.subplots(figsize=(16, 10))
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

# ── Line of best fit ──────────────────────────────────────────────────────────
slope, intercept, r, p, se = stats.linregress(plot_data['tempo'], plot_data['adj_margin'])
x_line = np.linspace(plot_data['tempo'].min() - 1, plot_data['tempo'].max() + 1, 100)
y_line = slope * x_line + intercept
ax.plot(x_line, y_line, color='steelblue', linewidth=1.5, linestyle='--',
        alpha=0.7, label='LOBF', zorder=2)

# ── Scatter ───────────────────────────────────────────────────────────────────
ax.scatter(plot_data['tempo'], plot_data['adj_margin'],
           color='steelblue', s=30, alpha=0.6, zorder=3, label='Teams')

# ── Team labels ───────────────────────────────────────────────────────────────
for _, row in plot_data.iterrows():
    ax.annotate(
        row['abbrev'],
        (row['tempo'], row['adj_margin']),
        fontsize=7.5,
        fontweight='bold',
        color='#222222',
        xytext=(4, 4),
        textcoords='offset points'
    )

# ── Trapezoid of Excellence (black outline, no fill) ─────────────────────────
# Shape: flat bottom ~adj_margin=25, wider at bottom, narrower at top
trap_coords = [
    (63.5, 25),   # bottom left
    (74.5, 25),   # bottom right
    (72.5, 37),   # top right
    (65.5, 37),   # top left
]
trap = patches.Polygon(
    trap_coords,
    closed=True,
    fill=False,
    edgecolor='black',
    linewidth=2.5,
    zorder=4
)
ax.add_patch(trap)
ax.text(67.5, 38.2, 'Ascertaining the Trapezoid of Excellence',
        fontsize=13, color='black', ha='center', fontweight='normal')

# ── Annotations ───────────────────────────────────────────────────────────────
ax.annotate("Too Fast!", xy=(75.2, 30), fontsize=12, color='black',
            fontstyle='italic')

ax.annotate("Don't be below the\nline of best fit!",
            xy=(63.0, 18), fontsize=10, color='black',
            fontstyle='italic',
            arrowprops=dict(arrowstyle='->', color='gray'),
            xytext=(62.5, 21))

# ── Formatting ────────────────────────────────────────────────────────────────
ax.set_xlabel('Pace (Possessions/40 Minutes)', fontsize=11, color='black')
ax.set_ylabel('Net Rating', fontsize=11, color='black')
ax.tick_params(colors='black')
ax.set_xlim(plot_data['tempo'].min() - 2, plot_data['tempo'].max() + 3)
ax.set_ylim(plot_data['adj_margin'].min() - 2, plot_data['adj_margin'].max() + 5)

for spine in ax.spines.values():
    spine.set_edgecolor('#cccccc')

ax.legend(loc='lower right', fontsize=9)
ax.grid(True, alpha=0.2, color='gray')

plt.tight_layout()
plt.savefig('trapezoid_excellence_v2.png', dpi=150, bbox_inches='tight', facecolor='white')
plt.show()

"""**TRAPEZOID OF EXCELLENCE (02/25)**"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from scipy import stats

# ── Use ALL teams, no filter ──────────────────────────────────────────────────
plot_data = bart_data.copy()
plot_data['abbrev'] = plot_data['team'].apply(abbreviate)

print("Tempo range:", plot_data['tempo'].min(), "-", plot_data['tempo'].max())
print("Adj margin range:", plot_data['adj_margin'].min(), "-", plot_data['adj_margin'].max())
print("Total teams:", len(plot_data))

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from scipy import stats

fig, ax = plt.subplots(figsize=(20, 12))
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

# ── Line of best fit ──────────────────────────────────────────────────────────
slope, intercept, r, p, se = stats.linregress(plot_data['tempo'], plot_data['adj_margin'])
x_line = np.linspace(41, 60, 200)
y_line = slope * x_line + intercept
ax.plot(x_line, y_line, color='steelblue', linewidth=1.5, linestyle='--', alpha=0.7, label='LOBF', zorder=2)

# ── Scatter all 364 teams ─────────────────────────────────────────────────────
ax.scatter(plot_data['tempo'], plot_data['adj_margin'],
           color='steelblue', s=25, alpha=0.5, zorder=3, label='Teams')

# ── Team labels ───────────────────────────────────────────────────────────────
for _, row in plot_data.iterrows():
    ax.annotate(
        row['abbrev'],
        (row['tempo'], row['adj_margin']),
        fontsize=5,
        fontweight='bold',
        color='#222222',
        xytext=(3, 3),
        textcoords='offset points'
    )

# ── Trapezoid fitted to actual data ranges ────────────────────────────────────
# Elite zone: above avg margin (~5+), mid-to-fast tempo
trap_coords = [
    (48.0, 5),    # bottom left
    (58.5, 5),    # bottom right
    (56.5, 13),   # top right
    (50.0, 13),   # top left
]
trap = patches.Polygon(
    trap_coords, closed=True, fill=False,
    edgecolor='green', linewidth=2.5, zorder=4
)
ax.add_patch(trap)
ax.text(51.5, 13.3, 'Trapezoid of Excellence', fontsize=10,
        color='green', fontweight='bold')

# ── Quadrant lines ────────────────────────────────────────────────────────────
ax.axhline(0, color='gray', linewidth=0.8, linestyle='-', alpha=0.4)
ax.axvline(plot_data['tempo'].mean(), color='gray', linewidth=0.8,
           linestyle='-', alpha=0.4)

# ── Annotations ───────────────────────────────────────────────────────────────
ax.annotate("Too Fast!", xy=(58.0, -5), fontsize=10, color='black', fontstyle='italic')
ax.annotate("Don't be below the\nline of best fit!",
            xy=(43.5, -8), fontsize=9, color='black', fontstyle='italic')

# ── Axis limits to show all 4 quadrants ──────────────────────────────────────
ax.set_xlim(41, 60)
ax.set_ylim(-25, 15)

# ── Labels ────────────────────────────────────────────────────────────────────
ax.set_xlabel('Pace (Possessions/40 Minutes)', fontsize=12, color='black')
ax.set_ylabel('Net Rating (Adj for Opponent)', fontsize=12, color='black')
ax.set_title('Trapezoid of Excellence\nPace x Adj Net Rating (2025)',
             fontsize=14, fontweight='bold', color='black', pad=15)
ax.tick_params(colors='black')
ax.grid(True, alpha=0.15, color='gray')
for spine in ax.spines.values():
    spine.set_edgecolor('#cccccc')

ax.legend(loc='lower right', fontsize=9)

plt.tight_layout()
plt.savefig('trapezoid_v3.png', dpi=150, bbox_inches='tight', facecolor='white')
plt.show()

"""**TRAPEZOID OF EXCELLENCE, NOW CONSTRAINED TO THE TOP 25 TEAMS**"""

# Top 25 teams by barthag (overall team strength)
top25 = bart_data.nlargest(25, 'barthag')[['team', 'barthag', 'adjoe', 'adjde', 'adj_margin', 'tempo']].reset_index(drop=True)
top25.index += 1
print(top25)

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from scipy import stats

fig, ax = plt.subplots(figsize=(16, 10))
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

# ── Line of best fit ──────────────────────────────────────────────────────────
slope, intercept, r, p, se = stats.linregress(top25['tempo'], top25['adj_margin'])
x_line = np.linspace(48, 60, 200)
y_line = slope * x_line + intercept
ax.plot(x_line, y_line, color='steelblue', linewidth=1.5, linestyle='--', alpha=0.7, label='LOBF', zorder=2)

# ── Scatter ───────────────────────────────────────────────────────────────────
ax.scatter(top25['tempo'], top25['adj_margin'],
           color='steelblue', s=60, alpha=0.7, zorder=3, label='Teams')

# ── Team labels ───────────────────────────────────────────────────────────────
for _, row in top25.iterrows():
    ax.annotate(
        row['team'],
        (row['tempo'], row['adj_margin']),
        fontsize=8.5,
        fontweight='bold',
        color='#222222',
        xytext=(5, 5),
        textcoords='offset points'
    )

# ── Trapezoid scaled to top 25 data ──────────────────────────────────────────
# Elite zone: high margin (8+) mid-to-fast tempo for this group
trap_coords = [
    (50.5, 8.0),   # bottom left
    (58.5, 8.0),   # bottom right
    (57.5, 13.5),  # top right
    (51.5, 13.5),  # top left
]
trap = patches.Polygon(
    trap_coords, closed=True, fill=False,
    edgecolor='green', linewidth=2.5, zorder=4
)
ax.add_patch(trap)
ax.text(52.0, 13.8, 'Trapezoid of Excellence',
        fontsize=10, color='green', fontweight='bold')

# ── Quadrant lines ────────────────────────────────────────────────────────────
ax.axhline(top25['adj_margin'].mean(), color='gray', linewidth=0.8, linestyle='--', alpha=0.5)
ax.axvline(top25['tempo'].mean(), color='gray', linewidth=0.8, linestyle='--', alpha=0.5)

# ── Quadrant labels ───────────────────────────────────────────────────────────
ax.text(48.5, 12.0, 'Slow & Elite\n(Pace Control)', fontsize=8,
        color='gray', fontstyle='italic', alpha=0.7)
ax.text(56.5, 12.0, 'Fast & Elite\n(Too Fast?)', fontsize=8,
        color='gray', fontstyle='italic', alpha=0.7)
ax.text(48.5, 3.0, 'Slow & Decent', fontsize=8,
        color='gray', fontstyle='italic', alpha=0.7)
ax.text(56.5, 3.0, 'Fast & Decent', fontsize=8,
        color='gray', fontstyle='italic', alpha=0.7)

# ── Axis limits ───────────────────────────────────────────────────────────────
ax.set_xlim(47, 60)
ax.set_ylim(2, 14.5)

# ── Labels ────────────────────────────────────────────────────────────────────
ax.set_xlabel('Pace (Possessions/40 Minutes)', fontsize=12)
ax.set_ylabel('Net Rating (Adj Margin)', fontsize=12)
ax.set_title('Trapezoid of Excellence — Top 25 Teams (2025)\nPace x Adj Net Rating',
             fontsize=14, fontweight='bold', pad=15)
ax.tick_params(colors='black')
ax.grid(True, alpha=0.15, color='gray')
for spine in ax.spines.values():
    spine.set_edgecolor('#dddddd')

ax.legend(loc='lower right', fontsize=9)

plt.tight_layout()
plt.savefig('trapezoid_top25.png', dpi=150, bbox_inches='tight', facecolor='white')
plt.show()